name=LapPCF8574
version=1.0.0
author=LucyAmy Photography
maintainer=Lucy Amanda Berry
sentence=PCF8574 driver
paragraph=An Arduino library to drive the PCF8574 I/O expander. It is small and simple, but likely lets you do what you need.
category=Other
architectures=*
includes=LapPCF8574.h
